export interface Jobs {
  id: string;
  title: string;
  location: string;
  type: string;
  status: "open" | "closed" | "draft";
  postedDate: string;
  applicants: number;
  department: string;
  company: string;
  companyLogo: string;
  experience: string;
  featured: boolean;
  urgent: boolean;
  views: number;
  expiryDate: string;
  salary: { min: number; max: number; currency: string };
  applications: number;
}

export interface Job {
  id: string;
  title: string;
  location: string;
  type: string;
  status: "open" | "closed" | "draft";
  postedDate: string;
  applicants: number;
}

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Frontend Developer",
    location: "London, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-01",
    applicants: 8,
  },
  {
    id: "2",
    title: "Backend Developer",
    location: "Remote",
    type: "Contract",
    status: "open",
    postedDate: "2024-05-28",
    applicants: 5,
  },
  {
    id: "3",
    title: "UI/UX Designer",
    location: "Manchester, UK",
    type: "Part-time",
    status: "closed",
    postedDate: "2024-05-15",
    applicants: 12,
  },
  {
    id: "4",
    title: "QA Tester",
    location: "Birmingham, UK",
    type: "Full-time",
    status: "draft",
    postedDate: "2024-06-10",
    applicants: 0,
  },
  {
    id: "5",
    title: "DevOps Engineer",
    location: "Remote",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-11",
    applicants: 3,
  },
  {
    id: "6",
    title: "Product Manager",
    location: "London, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-12",
    applicants: 7,
  },
  {
    id: "7",
    title: "Full Stack Developer",
    location: "Manchester, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-13",
    applicants: 10,
  },
  {
    id: "8",
    title: "Frontend Engineer",
    location: "Birmingham, UK",
    type: "Part-time",
    status: "closed",
    postedDate: "2024-06-14",
    applicants: 6,
  },
  {
    id: "9",
    title: "Backend Engineer",
    location: "London, UK",
    type: "Full-time",
    status: "draft",
    postedDate: "2024-06-15",
    applicants: 2,
  },
  {
    id: "10",
    title: "UI/UX Designer",
    location: "Manchester, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-16",
    applicants: 15,
  },
  {
    id: "11",
    title: "QA Tester",
    location: "Birmingham, UK",
    type: "Part-time",
    status: "closed",
    postedDate: "2024-06-17",
    applicants: 8,
  },
  {
    id: "12",
    title: "Full Stack Developer",
    location: "London, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-18",
    applicants: 12,
  },
  {
    id: "13",
    title: "Frontend Engineer",
    location: "Manchester, UK",
    type: "Part-time",
    status: "open",
    postedDate: "2024-06-19",
    applicants: 10,
  },
  {
    id: "14",
    title: "Backend Engineer",
    location: "Birmingham, UK",
    type: "Full-time",
    status: "closed",
    postedDate: "2024-06-20",
    applicants: 5,
  },
  {
    id: "15",
    title: "UI/UX Designer",
    location: "London, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-21",
    applicants: 18,
  },
  {
    id: "16",
    title: "QA Tester",
    location: "Manchester, UK",
    type: "Part-time",
    status: "closed",
    postedDate: "2024-06-22",
    applicants: 11,
  },
  {
    id: "17",
    title: "Full Stack Developer",
    location: "Birmingham, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-23",
    applicants: 14,
  },
  {
    id: "18",
    title: "Frontend Engineer",
    location: "London, UK",
    type: "Part-time",
    status: "open",
    postedDate: "2024-06-24",
    applicants: 9,
  },
  {
    id: "19",
    title: "Backend Engineer",
    location: "Manchester, UK",
    type: "Full-time",
    status: "closed",
    postedDate: "2024-06-25",
    applicants: 7,
  },
  {
    id: "20",
    title: "UI/UX Designer",
    location: "Birmingham, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-26",
    applicants: 13,
  },
  {
    id: "21",
    title: "QA Tester",
    location: "London, UK",
    type: "Part-time",
    status: "closed",
    postedDate: "2024-06-27",
    applicants: 6,
  },
  {
    id: "22",
    title: "Full Stack Developer",
    location: "Manchester, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-28",
    applicants: 16,
  },
  {
    id: "23",
    title: "Frontend Engineer",
    location: "Birmingham, UK",
    type: "Part-time",
    status: "open",
    postedDate: "2024-06-29",
    applicants: 11,
  },
  {
    id: "24",
    title: "Backend Engineer",
    location: "London, UK",
    type: "Full-time",
    status: "closed",
    postedDate: "2024-06-30",
    applicants: 8,
  },
  {
    id: "25",
    title: "UI/UX Designer",
    location: "Manchester, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-07-01",
    applicants: 19,
  },
];

export const defaultJobs: Jobs[] = [
  {
    id: "1",
    title: "Frontend Developer",
    location: "London, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-01",
    applicants: 8,
    department: "Engineering",
    company: "TechCorp",
    companyLogo: "/assets/logo.png",
    experience: "3+ years",
    featured: true,
    urgent: false,
    views: 120,
    expiryDate: "2024-07-01",
    salary: { min: 40000, max: 60000, currency: "GBP" },
    applications: 8,
  },
  {
    id: "2",
    title: "Backend Developer",
    location: "Remote",
    type: "Contract",
    status: "open",
    postedDate: "2024-05-28",
    applicants: 5,
    department: "Engineering",
    company: "Cloudify",
    companyLogo: "/assets/logo.png",
    experience: "2+ years",
    featured: false,
    urgent: true,
    views: 80,
    expiryDate: "2024-07-10",
    salary: { min: 45000, max: 65000, currency: "GBP" },
    applications: 5,
  },
  {
    id: "3",
    title: "UI/UX Designer",
    location: "Manchester, UK",
    type: "Part-time",
    status: "closed",
    postedDate: "2024-05-15",
    applicants: 12,
    department: "Design",
    company: "Designify",
    companyLogo: "/assets/logo.png",
    experience: "1+ years",
    featured: false,
    urgent: false,
    views: 60,
    expiryDate: "2024-06-15",
    salary: { min: 30000, max: 50000, currency: "GBP" },
    applications: 12,
  },
  {
    id: "4",
    title: "QA Tester",
    location: "Birmingham, UK",
    type: "Full-time",
    status: "draft",
    postedDate: "2024-06-10",
    applicants: 0,
    department: "Quality Assurance",
    company: "AssureIT",
    companyLogo: "/assets/logo.png",
    experience: "2+ years",
    featured: false,
    urgent: false,
    views: 50,
    expiryDate: "2024-06-20",
    salary: { min: 35000, max: 55000, currency: "GBP" },
    applications: 0,
  },
  {
    id: "5",
    title: "DevOps Engineer",
    location: "Remote",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-11",
    applicants: 3,
    department: "IT Operations",
    company: "OpsGen",
    companyLogo: "/assets/logo.png",
    experience: "4+ years",
    featured: true,
    urgent: true,
    views: 100,
    expiryDate: "2024-07-15",
    salary: { min: 50000, max: 70000, currency: "GBP" },
    applications: 3,
  },
  {
    id: "6",
    title: "Product Manager",
    location: "London, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-12",
    applicants: 7,
    department: "Product",
    company: "Prodigy",
    companyLogo: "/assets/logo.png",
    experience: "5+ years",
    featured: true,
    urgent: false,
    views: 150,
    expiryDate: "2024-07-20",
    salary: { min: 60000, max: 80000, currency: "GBP" },
    applications: 7,
  },
  {
    id: "7",
    title: "Full Stack Developer",
    location: "Manchester, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-13",
    applicants: 10,
    department: "Engineering",
    company: "Stackly",
    companyLogo: "/assets/logo.png",
    experience: "3+ years",
    featured: true,
    urgent: true,
    views: 180,
    expiryDate: "2024-07-25",
    salary: { min: 45000, max: 65000, currency: "GBP" },
    applications: 10,
  },
  {
    id: "8",
    title: "Frontend Engineer",
    location: "Birmingham, UK",
    type: "Part-time",
    status: "closed",
    postedDate: "2024-06-14",
    applicants: 6,
    department: "Engineering",
    company: "TechCorp",
    companyLogo: "/assets/logo.png",
    experience: "2+ years",
    featured: false,
    urgent: false,
    views: 70,
    expiryDate: "2024-06-25",
    salary: { min: 35000, max: 55000, currency: "GBP" },
    applications: 6,
  },
  {
    id: "9",
    title: "Backend Engineer",
    location: "London, UK",
    type: "Full-time",
    status: "draft",
    postedDate: "2024-06-15",
    applicants: 2,
    department: "Engineering",
    company: "Cloudify",
    companyLogo: "/assets/logo.png",
    experience: "1+ years",
    featured: false,
    urgent: false,
    views: 40,
    expiryDate: "2024-06-30",
    salary: { min: 30000, max: 50000, currency: "GBP" },
    applications: 2,
  },
  {
    id: "10",
    title: "UI/UX Designer",
    location: "Manchester, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-16",
    applicants: 15,
    department: "Design",
    company: "Designify",
    companyLogo: "/assets/logo.png",
    experience: "2+ years",
    featured: true,
    urgent: true,
    views: 200,
    expiryDate: "2024-07-30",
    salary: { min: 40000, max: 60000, currency: "GBP" },
    applications: 15,
  },
  {
    id: "11",
    title: "QA Tester",
    location: "Birmingham, UK",
    type: "Part-time",
    status: "closed",
    postedDate: "2024-06-17",
    applicants: 8,
    department: "Quality Assurance",
    company: "AssureIT",
    companyLogo: "/assets/logo.png",
    experience: "1+ years",
    featured: false,
    urgent: false,
    views: 90,
    expiryDate: "2024-07-05",
    salary: { min: 30000, max: 50000, currency: "GBP" },
    applications: 8,
  },
  {
    id: "12",
    title: "Full Stack Developer",
    location: "London, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-18",
    applicants: 12,
    department: "Engineering",
    company: "Stackly",
    companyLogo: "/assets/logo.png",
    experience: "3+ years",
    featured: true,
    urgent: true,
    views: 220,
    expiryDate: "2024-08-05",
    salary: { min: 45000, max: 65000, currency: "GBP" },
    applications: 12,
  },
  {
    id: "13",
    title: "Frontend Engineer",
    location: "Manchester, UK",
    type: "Part-time",
    status: "open",
    postedDate: "2024-06-19",
    applicants: 10,
    department: "Engineering",
    company: "TechCorp",
    companyLogo: "/assets/logo.png",
    experience: "2+ years",
    featured: false,
    urgent: false,
    views: 110,
    expiryDate: "2024-07-10",
    salary: { min: 35000, max: 55000, currency: "GBP" },
    applications: 10,
  },
  {
    id: "14",
    title: "Backend Engineer",
    location: "Birmingham, UK",
    type: "Full-time",
    status: "closed",
    postedDate: "2024-06-20",
    applicants: 5,
    department: "Engineering",
    company: "Cloudify",
    companyLogo: "/assets/logo.png",
    experience: "1+ years",
    featured: false,
    urgent: false,
    views: 55,
    expiryDate: "2024-06-25",
    salary: { min: 30000, max: 50000, currency: "GBP" },
    applications: 5,
  },
  {
    id: "15",
    title: "UI/UX Designer",
    location: "London, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-21",
    applicants: 18,
    department: "Design",
    company: "Designify",
    companyLogo: "/assets/logo.png",
    experience: "2+ years",
    featured: true,
    urgent: true,
    views: 250,
    expiryDate: "2024-08-10",
    salary: { min: 40000, max: 60000, currency: "GBP" },
    applications: 18,
  },
  {
    id: "16",
    title: "QA Tester",
    location: "Manchester, UK",
    type: "Part-time",
    status: "closed",
    postedDate: "2024-06-22",
    applicants: 11,
    department: "Quality Assurance",
    company: "AssureIT",
    companyLogo: "/assets/logo.png",
    experience: "1+ years",
    featured: false,
    urgent: false,
    views: 120,
    expiryDate: "2024-07-15",
    salary: { min: 30000, max: 50000, currency: "GBP" },
    applications: 11,
  },
  {
    id: "17",
    title: "Full Stack Developer",
    location: "Birmingham, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-23",
    applicants: 14,
    department: "Engineering",
    company: "Stackly",
    companyLogo: "/assets/logo.png",
    experience: "3+ years",
    featured: true,
    urgent: true,
    views: 280,
    expiryDate: "2024-08-15",
    salary: { min: 45000, max: 65000, currency: "GBP" },
    applications: 14,
  },
  {
    id: "18",
    title: "Frontend Engineer",
    location: "London, UK",
    type: "Part-time",
    status: "open",
    postedDate: "2024-06-24",
    applicants: 9,
    department: "Engineering",
    company: "TechCorp",
    companyLogo: "/assets/logo.png",
    experience: "2+ years",
    featured: false,
    urgent: false,
    views: 100,
    expiryDate: "2024-07-20",
    salary: { min: 35000, max: 55000, currency: "GBP" },
    applications: 9,
  },
  {
    id: "19",
    title: "Backend Engineer",
    location: "Manchester, UK",
    type: "Full-time",
    status: "closed",
    postedDate: "2024-06-25",
    applicants: 7,
    department: "Engineering",
    company: "Cloudify",
    companyLogo: "/assets/logo.png",
    experience: "1+ years",
    featured: false,
    urgent: false,
    views: 70,
    expiryDate: "2024-06-30",
    salary: { min: 30000, max: 50000, currency: "GBP" },
    applications: 7,
  },
  {
    id: "20",
    title: "UI/UX Designer",
    location: "Birmingham, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-26",
    applicants: 13,
    department: "Design",
    company: "Designify",
    companyLogo: "/assets/logo.png",
    experience: "2+ years",
    featured: true,
    urgent: true,
    views: 200,
    expiryDate: "2024-08-05",
    salary: { min: 40000, max: 60000, currency: "GBP" },
    applications: 13,
  },
  {
    id: "21",
    title: "QA Tester",
    location: "London, UK",
    type: "Part-time",
    status: "closed",
    postedDate: "2024-06-27",
    applicants: 6,
    department: "Quality Assurance",
    company: "AssureIT",
    companyLogo: "/assets/logo.png",
    experience: "1+ years",
    featured: false,
    urgent: false,
    views: 90,
    expiryDate: "2024-07-10",
    salary: { min: 30000, max: 50000, currency: "GBP" },
    applications: 6,
  },
  {
    id: "22",
    title: "Full Stack Developer",
    location: "Manchester, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-06-28",
    applicants: 16,
    department: "Engineering",
    company: "Stackly",
    companyLogo: "/assets/logo.png",
    experience: "3+ years",
    featured: true,
    urgent: true,
    views: 300,
    expiryDate: "2024-08-15",
    salary: { min: 45000, max: 65000, currency: "GBP" },
    applications: 16,
  },
  {
    id: "23",
    title: "Frontend Engineer",
    location: "Birmingham, UK",
    type: "Part-time",
    status: "open",
    postedDate: "2024-06-29",
    applicants: 11,
    department: "Engineering",
    company: "TechCorp",
    companyLogo: "/assets/logo.png",
    experience: "2+ years",
    featured: false,
    urgent: false,
    views: 130,
    expiryDate: "2024-07-20",
    salary: { min: 35000, max: 55000, currency: "GBP" },
    applications: 11,
  },
  {
    id: "24",
    title: "Backend Engineer",
    location: "London, UK",
    type: "Full-time",
    status: "closed",
    postedDate: "2024-06-30",
    applicants: 8,
    department: "Engineering",
    company: "Cloudify",
    companyLogo: "/assets/logo.png",
    experience: "1+ years",
    featured: false,
    urgent: false,
    views: 70,
    expiryDate: "2024-06-30",
    salary: { min: 30000, max: 50000, currency: "GBP" },
    applications: 8,
  },
  {
    id: "25",
    title: "UI/UX Designer",
    location: "Manchester, UK",
    type: "Full-time",
    status: "open",
    postedDate: "2024-07-01",
    applicants: 19,
    department: "Design",
    company: "Designify",
    companyLogo: "/assets/logo.png",
    experience: "2+ years",
    featured: true,
    urgent: true,
    views: 350,
    expiryDate: "2024-08-20",
    salary: { min: 40000, max: 60000, currency: "GBP" },
    applications: 19,
  },
];

export function getJobs(): Jobs[] {
  if (typeof window !== "undefined") {
    const stored = localStorage.getItem("recruiter_jobs");
    if (stored) return JSON.parse(stored);
  }
  return defaultJobs;
}

export function setJobs(jobs: Jobs[]) {
  if (typeof window !== "undefined") {
    localStorage.setItem("recruiter_jobs", JSON.stringify(jobs));
  }
}
